#!/bin/sh
DAEMON=/usr/bin/buttons_events
PIDFILE=/var/run/buttons_events.pid

case "$1" in
    start)
        echo "Starting button listener..."
        $DAEMON &
        ;;
    stop)
        echo "Stopping button listener..."
        if [ -f $PIDFILE ]; then
            kill "$(cat $PIDFILE)"
        fi
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac